export enum AppPages {
  TRY_US_FREE = 'try us free',
  TRY_US_FREE_APPLE_FITNESS_FREE_TRIAL = 'try us free apple fitness free trial',
  TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER = 'try us free apple fitness plus subscriber',
  BOOK_A_TOUR_STANDALONE = 'book a tour standalone',
  LOCAL_OFFER = 'local offer',
  GLOBAL_OFFER = 'global offer',
  MEMBER_OFFER = 'member offer',
  MEMBERSHIP_INQUIRY = 'membership inquiry',
  EVENTS_FREE_TRIAL_PASS = 'events free trial pass',
  EVENTS_TRAIN_FOR_YOUR_LIFE = 'events train for your life',
  EVENTS_JOIN_ONLINE = 'events join online',
  EVENTS_PROMO = 'events promo',
  EVENTS_FIND_YOUR_FITPHORIA = 'events find your fitphoria',
  EVENTS_BOOK_A_TOUR = 'events book a tour',
  CONTACT_US = 'contact us',
  CANCEL_MEMBERSHIP = 'cancel membership',
  CORPORATE_MEMBERSHIP = 'corporate membership',
  OWN_A_GYM = 'own a gym',
  INVITE_A_FRIEND = 'invite a friend',
}
