import { t } from '@utils/locale-utils/locale-manager';
import TranslationKeys from '@utils/locale-utils/translations-keys.constants';
import { AppPages } from './app-pages.enum';
import { PATHS } from './index';

export const BOOKING_MESSAGES: Record<string, string> = {
  [AppPages.TRY_US_FREE]: t(TranslationKeys.Texts.BookingConfirmation.TryUsFree),
  [AppPages.TRY_US_FREE_APPLE_FITNESS_FREE_TRIAL]: t(
    TranslationKeys.Texts.BookingConfirmation.AppleFitnessPlusFreeTrial,
  ),
  [AppPages.TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER]: t(
    TranslationKeys.Texts.BookingConfirmation.AppleFitnessPlusSubscriber,
  ),
  [AppPages.BOOK_A_TOUR_STANDALONE]: t(
    TranslationKeys.Texts.BookingConfirmation.BookATourStandalone,
  ),
  [AppPages.EVENTS_PROMO]: t(TranslationKeys.Texts.BookingConfirmation.EventsPromo),
  [AppPages.LOCAL_OFFER]: t(TranslationKeys.Texts.BookingConfirmation.LocalOffer),
  [AppPages.GLOBAL_OFFER]: t(TranslationKeys.Texts.BookingConfirmation.LocalOffer),
  [AppPages.MEMBER_OFFER]: t(TranslationKeys.Texts.BookingConfirmation.MemberOffer),
  [AppPages.MEMBERSHIP_INQUIRY]: t(TranslationKeys.Texts.BookingConfirmation.MembershipInquiry),
  [AppPages.EVENTS_FREE_TRIAL_PASS]: t(
    TranslationKeys.Texts.BookingConfirmation.EventsFreeTrialPass,
  ),
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: t(
    TranslationKeys.Texts.BookingConfirmation.EventsTrainForYourLife,
  ),
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: t(
    TranslationKeys.Texts.BookingConfirmation.EventsFindYourFitphoria,
  ),
  [AppPages.EVENTS_BOOK_A_TOUR]: t(TranslationKeys.Texts.BookingConfirmation.EventsBookATour),
  [AppPages.CORPORATE_MEMBERSHIP]: t(TranslationKeys.Texts.BookingConfirmation.CorporateMembership),
  [AppPages.INVITE_A_FRIEND]: t(TranslationKeys.Texts.BookingConfirmation.InviteAFriend),
};

export const VARIANT_MAP: Record<string, string> = {
  [AppPages.TRY_US_FREE]: 'addon',
  [AppPages.TRY_US_FREE_APPLE_FITNESS_FREE_TRIAL]: 'fitnessPlusNew',
  [AppPages.TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER]: 'fitnessPlus',
  [AppPages.BOOK_A_TOUR_STANDALONE]: 'standalone',
  [AppPages.LOCAL_OFFER]: 'addon',
  [AppPages.MEMBER_OFFER]: 'addon',
  [AppPages.MEMBERSHIP_INQUIRY]: 'addon',
  [AppPages.EVENTS_FREE_TRIAL_PASS]: 'addon',
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: 'addon',
  [AppPages.EVENTS_JOIN_ONLINE]: 'addon',
  [AppPages.EVENTS_PROMO]: 'addon',
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: 'addon',
  [AppPages.EVENTS_BOOK_A_TOUR]: 'addon',
};

export const TRY_US_FREE_VARIANT_MAP: Record<string, string> = {
  [AppPages.EVENTS_FREE_TRIAL_PASS]: 'event',
  [AppPages.TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER]: 'claimOffer',
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: 'event',
  [AppPages.EVENTS_JOIN_ONLINE]: 'event',
};

export const WORKFLOW_NAME_MAP: Record<string, string> = {
  [AppPages.TRY_US_FREE]: 'contact-nday',
  // Pixel catalog: Apple Fitness Free Trial Offer → nday-fplus-prospect (not TUF's contact-nday).
  [AppPages.TRY_US_FREE_APPLE_FITNESS_FREE_TRIAL]: 'nday-fplus-prospect',
  [AppPages.TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER]: 'fplus-offer-prospect',
  [AppPages.BOOK_A_TOUR_STANDALONE]: 'contact-nday',
  [AppPages.MEMBERSHIP_INQUIRY]: 'membership-inquiry',
  [AppPages.EVENTS_FREE_TRIAL_PASS]: 'contact-nday',
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: 'contact-nday',
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: 'membership-inquiry',
  [AppPages.EVENTS_BOOK_A_TOUR]: 'contact-nday',
  [AppPages.EVENTS_PROMO]: 'local-offer-unified',
  [AppPages.CONTACT_US]: 'contact-club',
  [AppPages.CANCEL_MEMBERSHIP]: 'cancel-membership',
  [AppPages.CORPORATE_MEMBERSHIP]: 'corporate-membership-inquiry',
};

export const LEAD_SOURCE_CODE_MAP: Record<string, string[]> = {
  // AR-SA (and some clubs) return Web-3day-3 for the national free-trial offer.
  [AppPages.TRY_US_FREE]: ['Web-1day-1', 'Web-7day-7', 'Web-3day-3'],
  [AppPages.TRY_US_FREE_APPLE_FITNESS_FREE_TRIAL]: ['Web-1day-FitnessPlus', 'Web-7day-FitnessPlus'],
  [AppPages.TRY_US_FREE_APPLE_FITNESS_PLUS_SUBSCRIBER]: ['Web-FitnessPlusSubscriber'],
  [AppPages.BOOK_A_TOUR_STANDALONE]: ['Web-VisitScheduled'],
  [AppPages.MEMBERSHIP_INQUIRY]: ['Web-PreMembership'],
  [AppPages.EVENTS_FREE_TRIAL_PASS]: ['Web-Event-7day-7', 'Web-Event-1day-1'],
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: ['Web-Event-7day-7', 'Web-Event-1day-1'],
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: ['Web-PreMembership'],
  [AppPages.EVENTS_BOOK_A_TOUR]: ['Web-VisitScheduled'],
  [AppPages.EVENTS_PROMO]: [
    'Web-Event-Join1DollarJuly2026_DC',
    'Website-Event-Basic_DC',
    'Website-Local-MayBirthday2026',
    // AU Events Promo (SIT) may return Event/_DC variant instead of Local catalog code.
    'Website-Event-MayBirthday2026_DC',
    'Website-Local-JoinGet2MonthsFree',
    // Events Promo (ZA/US catalog) returns Event/_DC variant for Join Get 2 Months Free.
    'Website-Event-JoinGet2MonthsFree_DC',
    // US/TH Events Promo campaign rotation — 6 Weeks Free / $0 to Join (observed on SIT/UAT).
    'Website-Event-6WeeksFree_DC',
    'Web-Event-7day-7',
    'Web-Event-1day-1',
    'Website-Event-GlucklichOhneBindung_DC',
    'Website-Event-GratisFinoAfineAnno_DC',
    // EN-CA / FR-CA Events Promo — AF Pixel Catalog AFW-3989 (Join for $1 Fall Membership).
    'Website-Event-JoinFor1DollarFallMembership_DC',
    // EN-CA Events Promo — AF Pixel Catalog AFW-3169 ($0 Enrollment; still listed Active).
    'Website-Event-0Enrollment_DC',
  ],
};

export const LOCAL_OFFER_WORKFLOW_MAP: Record<string, string> = {
  join_get_30_days_free: 'local-offer-join-and-get-thirty-days-free',
  free_training_session: 'local-offer-unified',
  free_month_training: 'local-offer-free-month-training',
  fifty_dollars_off_training: 'local-offer-fifty-dollars-off-training',
  seven_day_group_training_pass: 'local-offer-seven-day-group-training',
  free_training_experience: 'local-offer-unified',
  free_7_day_pass: 'local-offer-free-seven-day-pass',
  twenty_one_day_reboot: 'local-offer-unified',
  '21day_reboot': 'local-offer-unified',
  six_week_challenge: 'local-offer-unified',
  '6_week_challenge': 'local-offer-unified',
  join_get_rest_of_year_free: 'local-offer-join-and-get-rest-of-year-free',
  zero_dollar_enrollment: 'local-offer-zero-dollars-enrollment',
  founders_rate: 'local-offer-founders-rate',
  join_get_summer_free: 'local-offer-join-and-get-summer-free',
  join_for_1_dollar: 'local-offer-join-for-one-dollar',
  join_for_1_dollar_transformation_challenge: 'local-offer-join-for-1-transformation-challenge',
  five_day_free_trial: 'local-offer-free-five-day-pass',
  seven_day_free_trial: 'local-offer-free-seven-day-pass',
  three_day_free_trial: 'local-offer-unified',
  dollar_349_club_voucher: 'local-offer-three-forty-nine-club-voucher',
  six_for_six_weeks: 'local-offer-six-for-six-weeks',
  buddy_bundle: 'local-offer-buddy-bundle',
  four_weeks_free: 'local-offer-four-weeks-free',
  open_week: 'local-offer-open-week',
  two_months_free: 'local-offer-two-months-free',
  foundation_membership: 'local-offer-foundation-membership',
  real_af_reboot: 'local-offer-unified',
  one_day_pass: 'local-offer-unified',
  join_get_40_offer: 'local-offer-unified',
  fourteen_day_pass: 'local-offer-unified',
  festive_fitness_deals: 'local-offer-unified',
  anniversary_special_offers: 'local-offer-unified',
  exclusive_recovery_experience: 'local-offer-unified',
  complimentary_body_composition_analysis: 'local-offer-unified',
  free_expert_fitness_consultation: 'local-offer-unified',
  refer_earn_rewards: 'local-offer-unified',
  refer_new_member_get_a_month_free: 'local-offer-unified',
  four_weeks_for_eu4: 'local-offer-unified',
  get_started_for_r199: 'local-offer-unified',
  free_training_experience_frca: 'local-offer-unified',
  /** FR-CA — Available on Prod (sheet gid=378757103) */
  join_1_dollar_fall_membership: 'local-offer-unified',
  /** EN-PH — AFW-3842–AFW-3847 */
  student_membership: 'local-offer-unified',
  senior_citizen_membership: 'local-offer-unified',
  pwd_membership: 'local-offer-unified',
  pre_sale_membership: 'local-offer-unified',
  refresh_membership: 'local-offer-unified',
  welcome_pack: 'local-offer-unified',
  '0_enrollment_frca': 'local-offer-unified',
  join_get_rest_year_free_frca: 'local-offer-unified',
  refer_friend_get_registration_transformation_challenge: 'local-offer-unified',
  '6_week_challenge_frca': 'local-offer-unified',
  '21_day_reboot_frca': 'local-offer-unified',
  free_7_day_pass_frca: 'local-offer-unified',
  '50_off_training_frca': 'local-offer-unified',
  '1_month_training_frca': 'local-offer-unified',
  training_session_frca: 'local-offer-unified',
  '30_days_free_frca': 'local-offer-unified',
  join_get_summer_free_frca: 'local-offer-unified',
  join_for_1_frca: 'local-offer-unified',
  /** DE — Available on Prod */
  coaching_normal: 'local-offer-unified',
  coaching_plus: 'local-offer-unified',
  coaching_special: 'local-offer-unified',
  coaching_advanced: 'local-offer-unified',
  early_bird: 'local-offer-unified',
  basic: 'local-offer-unified',
  /** IT — Available on Prod */
  join_now_at_the_best_price_ever: 'local-offer-unified',
  join_for_1_euro_next_month_is_free: 'local-offer-unified',
  pro_rated_free_month: 'local-offer-unified',
  join_for_1_get_the_rest_of_the_year_free: 'local-offer-unified',
  join_for_1_and_starter_pack_included: 'local-offer-unified',
  prorated_promotion: 'local-offer-unified',
  /** GB — Available on Prod */
  first_month_free_for_you_and_a_friend: 'local-offer-unified',
  seven_day_trial: 'local-offer-unified',
  one_day_free_trial: 'local-offer-unified',
  one_month_free: 'local-offer-unified',
  /** AT — Available on Prod */
  happy_without_commitment: 'local-offer-unified',
  refer_a_friend_both_1_month_free: 'local-offer-unified',
  free_care_package: 'local-offer-unified',
  three_months_for_99: 'local-offer-unified',
  first_month_free: 'local-offer-unified',
  opening_offer: 'local-offer-unified',
  /** EN-CA — Available on Prod (sheet gid=400169017) */
  join_for_1_transformation_challenge: 'local-offer-unified',
  join_get_the_rest_of_the_year_free: 'local-offer-unified',
  '0_enrollment_offer': 'local-offer-unified',
  join_for_1: 'local-offer-unified',
  join_get_the_summer_free: 'local-offer-unified',
  /** EN-NZ — Pixel Catalog AFW-3622–3627 / AFW-3784 */
  up_to_4_weeks_free: 'local-offer-unified',
  '4_for_4_weeks': 'local-offer-unified',
  '6_for_6_weeks': 'local-offer-unified',
  limited_time_offer: 'local-offer-unified',
  '2_weeks_on_us': 'local-offer-unified',
  '6_weeks_free_0_to_join': 'local-offer-unified',
  '7_day_group_training': 'local-offer-unified',
  '50_off_training_offer': 'local-offer-unified',
  free_training_experience_enca: 'local-offer-unified',
  free_7_daypass: 'local-offer-unified',
};

export const GLOBAL_OFFER_WORKFLOW_MAP: Record<string, string> = {
  real_af_reboot: 'local-offer-unified',
  free_training_experience_offer: 'local-offer-unified',
  free_7_day_group_training_offer: 'local-offer-unified',
  get_30_days_free_offer: 'local-offer-unified',
  join_for_one_dollar_offer: 'local-offer-unified',
  free_7_day_pass_offer: 'local-offer-unified',
  free_training_session: 'local-offer-unified',
  one_month_free_training: 'local-offer-unified',
  fifty_dollars_off_training_package: 'local-offer-unified',
  six_week_challenge: 'local-offer-unified',
  join_get_rest_year_free: 'local-offer-unified',
  join_for_one_dollar_offer_bfg: 'local-offer-unified',
  free_7_day_pass_offer_bfg: 'local-offer-unified',
  join_get_summer_free: 'local-offer-unified',
  join_for_one_dollar_transformation_challenge_offer: 'local-offer-unified',
  join_for_one_dollar_transformation_challenge_offer_bfg: 'local-offer-unified',
  one_day_pass: 'local-offer-unified',
  join_get_40_offer_bfg: 'local-offer-unified',
  join_get_40_offer_of: 'local-offer-unified',
  join_get_40_offer_jw: 'local-offer-unified',
  fourteen_day_pass_jo: 'local-offer-unified',
  fourteen_day_pass_eh: 'local-offer-unified',
  fourteen_day_pass_jw: 'local-offer-unified',
};

export const MEMBER_OFFER_WORKFLOW_MAP: Record<string, string> = {
  join_transformation_challenge: 'member-transformation-challenge',
};

export const LOCAL_OFFER_LEAD_SOURCE_MAP: Record<string, string[]> = {
  join_get_30_days_free: ['Website-Local-30DayFree'],
  free_training_session: ['Website-Local-TrainingSession'],
  free_month_training: ['Website-Local-OneMonthTraining'],
  fifty_dollars_off_training: ['Website-Local-50OffTraining'],
  seven_day_group_training_pass: ['Website-Local-7DayGroupTraining'],
  free_training_experience: ['Website-Local-TrainingExperience'],
  free_7_day_pass: ['Website-Local-7DayPass'],
  twenty_one_day_reboot: ['Website-Local-21DayReboot'],
  '21day_reboot': ['Website-Local-21DayReboot'],
  six_week_challenge: ['Website-Local-6WeekChallenge'],
  '6_week_challenge': ['Website-Local-6WeekChallenge'],
  join_get_rest_of_year_free: ['Website-Local-JoinGetRestOfYear'],
  zero_dollar_enrollment: ['Website-Local-0Enrollment'],
  founders_rate: ['Website-Local-FoundersRate'],
  join_get_summer_free: ['Website-Local-JoinGetSummerFree'],
  join_for_1_dollar: ['Website-Local-Joinfor1dollar'],
  join_for_1_dollar_transformation_challenge: ['Website-Local-JoinTransformationChallenge'],
  five_day_free_trial: ['Website-Local-5DayFreeTrial'],
  seven_day_free_trial: ['Website-Local-7DayFreeTrial'],
  three_day_free_trial: ['Website-Local-3DayFreeTrial'],
  dollar_349_club_voucher: ['Website-Local-349ClubVoucher'],
  six_for_six_weeks: ['Website-Local-6for6weeks', 'Website-Local-6For6Weeks'],
  buddy_bundle: ['Website-Local-BuddyBundle'],
  four_weeks_free: ['Website-Local-4WeeksFree'],
  open_week: ['Website-Local-OpenWeek'],
  two_months_free: ['Website-Local-LCC2Months'],
  foundation_membership: ['Website-Local-Foundation'],
  real_af_reboot: ['Website-Local-21DayReboot'],
  one_day_pass: ['Website-Local-1DayPass'],
  join_get_40_offer: ['Website-Local-JoinGet40Offer'],
  fourteen_day_pass: ['Website-Local-14DayPass'],
  /** SG — AFW-3440 welcome-pack */
  welcome_pack: ['Website-Local-WelcomePack'],
  festive_fitness_deals: ['Website-Local-FestiveFitnessDeals'],
  anniversary_special_offers: ['Website-Local-AnniversarySpecialOffers'],
  exclusive_recovery_experience: ['Website-Local-ExclusiveRecoveryExperience'],
  complimentary_body_composition_analysis: ['Website-Local-ComplimentaryBodyCompositionAnalysis'],
  free_expert_fitness_consultation: ['Website-Local-FreeExpertFitnessConsultation'],
  refer_earn_rewards: ['Website-Local-ReferEarnRewards'],
  refer_new_member_get_a_month_free: ['Website-Local-ReferNewMemberGetFreeMonth'],
  four_weeks_for_eu4: ['Website-Local-4WeeksFor4'],
  get_started_for_r199: ['Website-Local-GetStartedForR199'],
  free_training_experience_frca: ['Website-Local-ExperienceEntrainementGratuite'],
  /**
   * EN-CA / FR-CA — AFW-3989 Fall Membership national offer (Pixel Catalog).
   * Prefer Website-Local-JoinFor1DollarFallMembership; keep Joinfor1dollar as legacy alias.
   */
  join_1_dollar_fall_membership: [
    'Website-Local-JoinFor1DollarFallMembership',
    'Website-Local-Joinfor1dollar',
  ],
  /** EN-PH — AFW-3842–AFW-3847 (Pixel Catalog / JIRA lead_source_code) */
  student_membership: ['Website-Local-StudentMembership'],
  senior_citizen_membership: ['Website-Local-SeniorCitizenMembership'],
  pwd_membership: ['Website-Local-PWDMembership'],
  pre_sale_membership: ['Website-Local-PreSaleMembership'],
  refresh_membership: ['Website-Local-RefreshMembership'],
  '0_enrollment_frca': ['Website-Local-0Enrollment', 'Website-Local-RAMP-0Enrollment'],
  join_get_rest_year_free_frca: ['Website-Local-JoinGetRestOfYear'],
  refer_friend_get_registration_transformation_challenge: [
    'Website-Local-JoinTransformationChallenge',
  ],
  '6_week_challenge_frca': ['Website-Local-6WeekChallenge'],
  '21_day_reboot_frca': ['Website-Local-21DayReboot'],
  free_7_day_pass_frca: ['Website-Local-7DayPass'],
  '50_off_training_frca': ['Website-Local-50OffTraining'],
  '1_month_training_frca': ['Website-Local-OneMonthTraining'],
  training_session_frca: ['Website-Local-TrainingSession'],
  '30_days_free_frca': ['Website-Local-30DayFree'],
  join_get_summer_free_frca: ['Website-Local-JoinGetSummerFree'],
  join_for_1_frca: ['Website-Local-Joinfor1dollar'],
  /** DE — Available on Prod */
  coaching_normal: ['Website-Local-CoachingNormal'],
  coaching_plus: ['Website-Local-CoachingPlus'],
  coaching_special: ['Website-Local-CoachingSpecial'],
  coaching_advanced: ['Website-Local-CoachingAdvanced'],
  early_bird: ['Website-Local-EarlyBird'],
  basic: ['Website-Local-Basic'],
  /** IT — Available on Prod (pixel catalog) */
  join_now_at_the_best_price_ever: ['Website-Local-MigliorPrezzoDiSempre'],
  join_for_1_euro_next_month_is_free: ['Website-Local-1EuroMeseGratis'],
  pro_rated_free_month: ['Website-Local-ProRataMeseGratuito'],
  join_for_1_get_the_rest_of_the_year_free: ['Website-Local-GratisFinoAfineAnno'],
  join_for_1_and_starter_pack_included: ['Website-Local-PromoStarterPack'],
  prorated_promotion: ['Website-Local-PromoProRata'],
  /** GB — Available on Prod (pixel catalog; note catalog typo Fisrt) */
  first_month_free_for_you_and_a_friend: ['Website-Local-FisrtMonthFreeForYouAndAFriend'],
  seven_day_trial: ['Website-Local-7DayTrial'],
  one_day_free_trial: ['Website-Local-1DayFreeTrial'],
  one_month_free: ['Website-Local-1MonthFree'],
  /** AT — Available on Prod (pixel catalog) */
  happy_without_commitment: ['Website-Local-GlucklichOhneBindung'],
  refer_a_friend_both_1_month_free: ['Website-Local-DoppelteFreude'],
  free_care_package: ['Website-Local-KostenlosCarepaket'],
  three_months_for_99: ['Website-Local-3MonateFur99'],
  first_month_free: ['Website-Local-1MonatGratis'],
  opening_offer: ['Website-Local-Eroffnungsangebot'],
  /** EN-CA — Available on Prod (sheet gid=400169017; lead sources aligned to AF Pixel Catalog US equivalents) */
  join_for_1_transformation_challenge: ['Website-Local-JoinTransformationChallenge'],
  join_get_the_rest_of_the_year_free: ['Website-Local-JoinGetRestOfYear'],
  '0_enrollment_offer': ['Website-Local-0Enrollment', 'Website-Local-RAMP-0Enrollment'],
  join_for_1: ['Website-Local-Joinfor1dollar', 'Website-Local-JoinFor1'],
  /** EN-NZ — Pixel Catalog AFW-3622–3627 / AFW-3784 */
  up_to_4_weeks_free: ['Website-Local-UpTo4WeeksFree'],
  '4_for_4_weeks': ['Website-Local-4For4Weeks'],
  '6_for_6_weeks': ['Website-Local-6For6Weeks', 'Website-Local-6for6weeks'],
  limited_time_offer: ['Website-Local-LimitedTimeOffer'],
  '2_weeks_on_us': ['Website-Local-2WeeksOnUs'],
  '6_weeks_free_0_to_join': ['Website-Local-6WeeksFree'],
  join_get_the_summer_free: ['Website-Local-JoinGetSummerFree'],
  '7_day_group_training': ['Website-Local-7DayGroupTraining'],
  '50_off_training_offer': ['Website-Local-50OffTraining'],
  free_training_experience_enca: ['Website-Local-TrainingExperience'],
  free_7_daypass: ['Website-Local-7DayPass'],
};

export const GLOBAL_OFFER_LEAD_SOURCE_MAP: Record<string, string[]> = {
  real_af_reboot: ['Website-Local-21DayReboot'],
  free_training_experience_offer: ['Website-Local-TrainingExperience'],
  free_7_day_group_training_offer: ['Website-Local-7DayGroupTraining'],
  get_30_days_free_offer: ['Website-Local-30DayFree'],
  join_for_one_dollar_offer: ['Website-Local-Joinfor1dollar'],
  free_7_day_pass_offer: ['Website-Local-7DayPass'],
  free_training_session: ['Website-Local-TrainingSession'],
  one_month_free_training: ['Website-Local-OneMonthTraining'],
  fifty_dollars_off_training_package: ['Website-Local-50OffTraining'],
  six_week_challenge: ['Website-Local-6WeekChallenge'],
  join_get_rest_year_free: ['Website-Local-JoinGetRestOfYear'],
  join_for_one_dollar_offer_bfg: ['Website-Local-Joinfor1dollar'],
  free_7_day_pass_offer_bfg: ['Website-Local-7DayPass'],
  join_get_summer_free: ['Website-Local-JoinGetSummerFree'],
  join_for_one_dollar_transformation_challenge_offer: ['Website-Local-JoinTransformationChallenge'],
  join_for_one_dollar_transformation_challenge_offer_bfg: [
    'Website-Local-JoinTransformationChallenge',
  ],
  one_day_pass: ['Website-Local-1DayPass'],
  join_get_40_offer_bfg: ['Website-Local-JoinGet40Offer'],
  join_get_40_offer_of: ['Website-Local-JoinGet40Offer'],
  join_get_40_offer_jw: ['Website-Local-JoinGet40Offer'],
  fourteen_day_pass_jo: ['Website-Local-14DayPass'],
  fourteen_day_pass_eh: ['Website-Local-14DayPass'],
  fourteen_day_pass_jw: ['Website-Local-14DayPass'],
};

export const EVENTS_IFRAME_MAP: Record<string, string> = {
  [AppPages.EVENTS_FREE_TRIAL_PASS]: 'tuf-train-for-your-life-event-iframe',
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: 'tuf-train-for-your-life-event-iframe',
  [AppPages.EVENTS_JOIN_ONLINE]: 'tuf-train-for-your-life-event-iframe',
  [AppPages.EVENTS_PROMO]: 'tuf-train-for-your-life-event-iframe',
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: 'tuf-train-for-your-life-event-iframe',
  [AppPages.EVENTS_BOOK_A_TOUR]: 'tuf-train-for-your-life-event-iframe',
};

export const EVENTS_PAGE_PATH_MAP: Record<string, string> = {
  [AppPages.EVENTS_FREE_TRIAL_PASS]: PATHS.EVENTS_FREE_TRIAL_PASS,
  [AppPages.EVENTS_TRAIN_FOR_YOUR_LIFE]: PATHS.EVENTS_TRAIN_FOR_YOUR_LIFE,
  [AppPages.EVENTS_JOIN_ONLINE]: PATHS.EVENTS_JOIN_ONLINE,
  [AppPages.EVENTS_PROMO]: PATHS.EVENTS_PROMO,
  [AppPages.EVENTS_FIND_YOUR_FITPHORIA]: PATHS.EVENTS_FIND_YOUR_FITPHORIA,
  [AppPages.EVENTS_BOOK_A_TOUR]: PATHS.EVENTS_BOOK_A_TOUR,
};
